services:
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - proxy

  db:
    image: postgres
    container_name: patch-db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
      POSTGRES_DB: catalog
      restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - catalog-migrations:/migrations/catalog
    networks:
      - proxy

  catalog:
    container_name: patch-catalog
    build:
      context: ./
      dockerfile: ./dockerfiles/Catalog.dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - proxy
    volumes:
      - books:/app/books
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: catalog
      DB_PORT: ${DB_PORT}

volumes:
  postgres-data:
  catalog-migrations:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./src/catalog/migrations
  books:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./src/catalog/books

networks:
  proxy:
    name: proxy
